### ISSUE TITLE
Impossible to initialize Client with from_env()

### ISSUE THREAD

**Issue by thomasmost** [ammubhave/plaid-rs#2]
Pretty sure this code is broken:
```rs
let plaid_environment = match &std::env::var("PLAID_ENVIRONMENT")
        .expect("Missing environment variable: PLAID_ENVIRONMENT. Must be set to SANDBOX, DEVELOPMENT or PRODUCTION")
        .to_string().to_lowercase()[..] {
            "SANDBOX" => Environment::Sandbox,
            "DEVELOPMENT" => Environment::Development,
            "PRODUCTION" => Environment::Production,
            s => panic!("Environment variable PLAID_ENVIRONMENT must be set to SANDBOX, DEVELOPMENT or PRODUCTION. Is actually {}", s),
        };
```
...as the environment is lower-cased *before* being matched agains the upper-cased environment names

**Comment by kurtbuilds** [comment]
Hey @thomasmost Amol just gave me access to take over maintenance of this library.

The 2.x branch is now at https://github.com/libninjacom/plaid-rs, but the crate name remains `plaid`.

You'll see that this bug is fixed from that version forward. Note, it uses `PLAID_ENV`, not `PLAID_ENVIRONMENT`.

**Comment by thomasmost** [comment]
Hi @kurtbuilds—I have a fork that is now significantly more advanced, with several bug fixes here: https://github.com/Bend-Green/plaid-rs

Recommendation on how to proceed?

**Comment by kurtbuilds** [comment]
I looked at your fork. The features I see you added:

- de/serialize for some of the structs
- bugfix for environment
- adding/fixing the transactions_sync endpoint
- cursor support for transactions_sync

Let me know if I'm missing anything.

All of those should already work/be implemented in the new implementation. If you're comfortable updating to 2.x and any of that doesn't work, let me know and I'll work on fixes.

**Comment by thomasmost** [comment]
Thanks, @kurtbuilds. There are quite a few errors when I upgrade, so I'll have to set aside time for it later this week or next.

**Comment by kurtbuilds** [comment]
Let me know if you encounter issues!
